spring:
  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT}/${DB_NAME_DEV}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  ai:
    google:
      genai:
        api-key: ${GEMINI_KEY}
        chat:
          options:
            model: gemini-2.0-flash
            temperature: 0.0